import { InternalUserRow, InternalUsersStats } from "@/src/projects/admin-dashboard/internal/services/internal-users.service";

export const previewInternalUsersStats: InternalUsersStats = {
  total_internal_users: 4,
  active_internal_users: 4,
  verified_internal_users: 4,
  super_admins: 1,
  admins: 3,
  recent_30d: 2,
};

export const previewInternalUsersRows: InternalUserRow[] = [
  {
    id: "internal-1",
    email: "nadia@qalyas.com",
    first_name: "Nadia",
    last_name: "El Mansouri",
    phone: "+212600000111",
    is_active: true,
    is_verified: true,
    is_staff: true,
    is_superuser: true,
    role_key: "super_admin",
    created_at: "2026-03-01T09:00:00Z",
    last_login: "2026-04-12T08:30:00Z",
  },
  {
    id: "internal-2",
    email: "youssef@qalyas.com",
    first_name: "Youssef",
    last_name: "Haddad",
    phone: "+212600000222",
    is_active: true,
    is_verified: true,
    is_staff: true,
    is_superuser: false,
    role_key: "admin",
    created_at: "2026-03-04T09:00:00Z",
    last_login: "2026-04-11T16:15:00Z",
  },
  {
    id: "internal-3",
    email: "support@qalyas.com",
    first_name: "Sara",
    last_name: "Alaoui",
    phone: "+212600000333",
    is_active: true,
    is_verified: true,
    is_staff: true,
    is_superuser: false,
    role_key: "admin",
    created_at: "2026-03-20T09:00:00Z",
    last_login: "2026-04-10T14:00:00Z",
  },
  {
    id: "internal-4",
    email: "ops@qalyas.com",
    first_name: "Imane",
    last_name: "Tech",
    phone: "+212600000444",
    is_active: true,
    is_verified: true,
    is_staff: true,
    is_superuser: false,
    role_key: "admin",
    created_at: "2026-04-06T09:00:00Z",
    last_login: null,
  },
];